

target 'RXVerifyExample' do
#pod 'YYText'
#pod 'YYImage'
#pod 'YYModel'
#pod 'YYCategories'
#pod 'YYCache'
#pod 'YYAsyncLayer'
#pod 'YYDispatchQueuePool'

pod 'RXView'

pod 'RXImagePickManager'
pod 'YYKit'

pod 'AliyunOSSiOS'

pod 'RXCoreText'
pod 'RXVCMediator'

pod 'RXVerifyButton'

pod 'RXTextView'

pod 'RXPaddingView'

pod 'RXCategory'

pod 'RX3_XGPush'

pod 'RXScrollView'
pod 'RXPopView'

pod 'RXAppDefine'



pod 'AFNetworking'

pod 'Aspects'

pod 'RX3_TencentLiteSDK'
end

